### ISSUE TITLE
[Issue] Reward Items for classes

### ISSUE THREAD

**Issue by Th3AnG3L** [azerothcore/mod-congrats-on-level#22]
Hello please update the code to support different races.
If human reach lvl 10 reward item that can use him
if orc,elf, and all other to give other item.

Example if i want to award them maunt, only humans can learn horse riding the others cannot.
Need improvement option by race

**Comment by pangolp** [comment]
In order to do this, we would really have to move all the awards to the database, and within it, set an attribute that is the class, so that the awards can be delivered, not only by level, but also by class or race.
