### ISSUE TITLE
Coarse Sharpening Stone

### ISSUE THREAD

**Issue by Ohnoto** [azerothcore/mod-congrats-on-level#24]
Coarse Sharpening Stone is not able to be used on the weapon Verigan's Fist.

**Comment by pangolp** [comment]
> Coarse Sharpening Stone is not able to be used on the weapon Verigan's Fist.

Greetings. I don't understand how that item relates to this mod. The mod, advertises and gives out prizes as far as I remember. I need more information to understand your report.

**Comment by Ohnoto** [comment]
I'm sorry... I didn't realize I was commenting under a mod. I meant to comment on the master for Azerothcore.
