### ISSUE TITLE
Bug: While Compiling

### ISSUE THREAD

**Issue by cptcl** [azerothcore/mod-congrats-on-level#32]
### Current Behaviour

/root/azerothcore-wotlk/modules/mod-congrats-on-level/src/mod_congratsonlevel.cpp:82:176: fatal error: no member named 'getLevel' in 'Player'; did you mean 'GetLevel'?
    QueryResult result = WorldDatabase.Query("SELECT * FROM `mod_congrats_on_level_items` WHERE `level`={} AND (`race`={} OR `race`=0) AND (`class`={} OR `class`=0)", player->getLevel(), player->getRace(), player->getClass());
                                                                                                                                                                               ^~~~~~~~
                                                                                                                                                                               GetLevel
/root/azerothcore-wotlk/src/server/game/Entities/Unit/Unit.h:1509:25: note: 'GetLevel' declared here
    [[nodiscard]] uint8 GetLevel() const { return uint8(GetUInt32Value(UNIT_FIELD_LEVEL)); }
                        ^
1 error generated.
gmake[2]: *** [modules/CMakeFiles/modules.dir/build.make:188: modules/CMakeFiles/modules.dir/mod-congrats-on-level/src/mod_congratsonlevel.cpp.o] Fehler 1
gmake[2]: *** Es wird auf noch nicht beendete Prozesse gewartet....

### Expected Behaviour

No fatal error

### Steps to reproduce the problem

1. Update Acore & Playerbots
2. Clone git of this bautiful congratz module
3. Compile
4. look at around 13% of compiling

### AC rev. hash/commit

Cannot get copiled the server

### Operating system

Server Debian 12 latest

**Comment by cptcl** [comment]
It seems the "getLevel" in the cpp file will make troubles... changed all to "GetLevel" fixed the problem for me

**Comment by Helias** [comment]
please [open a PR](https://www.azerothcore.org/wiki/how-to-create-a-pr) to share the fix

**Comment by pangolp** [comment]
@Helias This problem was already solved in the following PR, but it was not linked, so it was not closed when doing the merge. It can be closed. https://github.com/azerothcore/mod-congrats-on-level/pull/33
