### ISSUE TITLE
No reward every 10 levels

### ISSUE THREAD

**Issue by Tiburan** [azerothcore/mod-congrats-on-level#9]
Expected behaviour: 

Reward every 10 levels, instead there is only a chat notification and a notice that there is no room in the players inventory.

**Comment by milestorme** [comment]
cannot reproduce, rewards working fine , didnt try with full bags though

**Comment by BarbzYHOOL** [comment]
I get no message and yes I receive no reward as well. I managed to get some rewards on a level 80 character but it's 100% inconsistent I don't understand the bug

**Comment by BarbzYHOOL** [comment]
Alright, I checked the code, it rewards ONLY when you are from level x9 to y0, example:

Works fine:
9->10 
79->80

Doesn't work:
5->10
4->80


So the module is working fine for only one case, blizzlike progression.
If you're trying to grant them level up with commands or something else, it won't trigger.

**This must be added to the module**
